### ISSUE TITLE
white page

### ISSUE THREAD

**Issue by antoine-castex** [forseti-security/forseti-visualizer#28]
Tyring to use the solution in Cloud Shell

open the web preview , icon of Forseti loaded but blank page 

how to troubleshoot ?

**Comment by garrettwong** [comment]
Want to confirm that you have referenced the instructions on the main page README.md:
[https://github.com/forseti-security/forseti-visualizer](https://github.com/forseti-security/forseti-visualizer)?

Recommend trying to reference in sequential order the instructions on the README.md. From my experience, if a white page comes up, usually the step around copying the forseti-visualizer-ui/dist needed to be re-run.

**Comment by gkowalski-google** [comment]
Hi @antoine-castex, any luck getting this to work?

**Comment by garrettwong** [comment]
Hi @antoine-castex, any luck getting this to work?

**Comment by garrettwong** [comment]
Let us know if any further assistance can be provided.  Thanks.  Will close this request.
