### ISSUE TITLE
Switch to GAE ?

### ISSUE THREAD

**Issue by antoine-castex** [forseti-security/forseti-visualizer#29]
Is there any plan to switch from local host the interface to GAE ?

**Comment by garrettwong** [comment]
Not currently, but would be open to reviewing a PR if someone wanted to contribute it.  In the infrastructure sub folder, we support multiple deployments for GCE, GKE, Cloud Run.

**Comment by garrettwong** [comment]
Parking lotting this request.  Tagged as 'good first issue' and 'help wanted'

**Comment by garrettwong** [comment]
An example App Engine app.yaml has been added to this branch here:

- https://github.com/forseti-security/forseti-visualizer/blob/grpc-fixes/forseti-api/app.yaml

The next steps are to provide documentation around this.  

Today, this can be done by:
1. Deploying Forseti Security
2. Updating the app.yaml config file to reflect the Forseti Security & Cloud SQL DB parameters
3. `gcloud app deploy` within the forseti-api/ directory

**Comment by garrettwong** [comment]
#58 provides deployment samples for App Engine / App Engine Flex.
