### ISSUE TITLE
Security vulnerability report for eslint-utils 

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-visualizer#31]
eslint-utils vulnerability found in forseti-api/package-lock.json 2 days ago
Remediation
Upgrade eslint-utils to version 1.4.1 or later. For example:

"dependencies": {
  "eslint-utils": ">=1.4.1"
}
or…
"devDependencies": {
  "eslint-utils": ">=1.4.1"
}
Always verify the validity and compatibility of suggestions with your codebase.

Details
GHSA-3gx7-xhv7-5mx3 More information
critical severity
Vulnerable versions: >= 1.2.0, < 1.4.1
Patched version: 1.4.1
'getStaticValue' function can execute arbitrary code
Impact
getStaticValue function can execute arbitrary code.

Patches
This problem has been patched in 1.4.1. Please update eslint-utils.

Workarounds
Don't use getStaticValue function, getStringIfConstant function, and getPropertyName function.

For more information
If you have any questions or comments about this advisory:

Open an issue in eslint-utils

**Comment by red2k18** [comment]
https://github.com/forseti-security/forseti-visualizer/pull/32 addresses this.

**Comment by garrettwong** [comment]
Merged
