### ISSUE TITLE
model handle in env config 

### ISSUE THREAD

**Issue by peter-fe** [forseti-security/forseti-visualizer#36]
Hi,

Sorry for putting that in an issue, I was not able to join your slack to place that there.

Currently it seems that I need to know the model handle more or less at compile/run time to support the IAM feature.

> export FORSETI_DATA_MODEL_HANDLE="[DATA_MODEL_HANDLE_HASH:21254f1de747879237a95cb552e80844]"

I have set up Forseti on GCE using the [Terraform module](https://github.com/forseti-security/terraform-google-forseti), so the scans are managed by a cron, that is running every 2 hours.

The [run_forseti.sh](https://github.com/forseti-security/forseti-security/blob/dev/install/gcp/scripts/run_forseti.sh) script that gets executed by the cron job, creates a new model/inventory for every run and does a cleanup of these after execution.

So I'm not sure how to align that with the visualizer to integrate with the existing setup.

Best,
Peter

**Comment by gkowalski-google** [comment]
@garrettwong Is the model handle required for all functionality, or just for the explain? If no model is specified, what if we just use the latest model found in the database?

**Comment by garrettwong** [comment]
@gkowalski-google @peter-fe - sorry for the delay.

The model needs to be better documented, but:
- It is not required to be populated
- It requires the referenced model to exist in the database (and not destroyed - contrary to the normal forseti flow)

In order to get this to work, you would have to run through the manual model creation in forseti.

```bash
forseti inventory create
forseti model create --inventory_index_id $INVENTORY_INDEX_ID # from `inventory create`
forseti model use $MODEL # from `model create`
forseti scanner run
```

**Comment by peter-fe** [comment]
Hi @garrettwong, @gkowalski-google,

Thank you for getting back on this!

But isn't the model, that was statically created (as suggested), getting out of sync with the data that gets collected through the automated Forseti scanner runs done by the cron?

So it would be more of a one time snapshot of the infrastructure and has to get re- created if I like to have an updated view of my resources & permissions?

**Comment by garrettwong** [comment]
That is correct - the model is a snapshot of the data in time (based on the inventory index id).  Ideally, the internal code should be updated to handle either dynamic model creation and selection.
