### ISSUE TITLE
Versions of handlebars prior to 4.0.14 are vulnerable to Prototype Pollution

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-visualizer#4]
Remediation
Upgrade handlebars to version 4.1.2 or later. For example:

"dependencies": {
  "handlebars": ">=4.1.2"
}
or…
"devDependencies": {
  "handlebars": ">=4.1.2"
}
Always verify the validity and compatibility of suggestions with your codebase.

Details
WS-2019-0064 More information
high severity
Vulnerable versions: >= 4.1.0, < 4.1.2
Patched version: 4.1.2
Versions of handlebars prior to 4.0.14 are vulnerable to Prototype Pollution. Templates may alter an Objects' prototype, thus allowing an attacker to execute arbitrary code on the server.

**Comment by garrettwong** [comment]
Applied security fix #6
