### ISSUE TITLE
FORSETIVISUALIZER not working when we include GKE in the filter resouces

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [forseti-security/forseti-visualizer#41]
FORSETIVISUALIZER not working when we include GKE in the filter by resouces type , it shows a bank screen .

**Comment by garrettwong** [comment]
Would need additional information, such as the Array of JSON Resources to diagnose exactly what is happening.

**Comment by garrettwong** [comment]
I'm unable to reproduce.  Will keep this monitoring this request, but further debugging would need a snapshot of where the code / data payload appears to be failing / causing an issue.

**Comment by garrettwong** [comment]
Not enough information to debug this.  Closing Issue.
