### ISSUE TITLE
Remove violations from forseti visualizer . 

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [forseti-security/forseti-visualizer#42]
I have to limit the forseti visualizer only for viewing the org level resources and not displaying violations. i reset the flag to on showViolations: false on  Body.vue and Navbar.vue , but still it displays the violations on the visualizer. Please let me know the steps to follow on this

**Comment by gkowalski-google** [comment]
@ajayakumar-jayaraj After changing those settings, did you re-run `npm run build` and redeploy the application? Which platform do you have Visualizer deployed on?

**Comment by garrettwong** [comment]
There are two `showViolations` flags.  One consists of the data of the parent component, and the other one would be that of the child component.  Can you confirm what happens if you set both to false?

**Comment by garrettwong** [comment]
Added 'question' label.

**Comment by garrettwong** [comment]
A `showViolations` flag has been added within a previous iteration of the code base.  Closing Issue.
