### ISSUE TITLE
forseti-visualizer is not showing all the resources .

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [forseti-security/forseti-visualizer#43]
Team , The forseti-visualizer right now is discovering only gke resource . it is not showing up any other resources like gcs , bigquery , compute etc .. Please look into it . thanks.

**Comment by garrettwong** [comment]
We'll be releasing a few new updates (PR) which should provide improved debugging around this if it still occurs.  

The easiest way to verify what may be going wrong would be to have a copy of the JSON payload, if you don't mind sharing that.

**Comment by garrettwong** [comment]
Not enough information to debug this.  Closing Issue.
