### ISSUE TITLE
Update serialize-javascript for security vulnerability

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-visualizer#48]
## Story
[There is a security alert in GitHub to update the serialize-javascript package due to a XSS vulnerability](https://github.com/forseti-security/forseti-visualizer/network/alert/forseti-visualizer-ui/package-lock.json/serialize-javascript/open). This package is not listed in the package.json file, but is found in the [package-lock.json](https://github.com/forseti-security/forseti-visualizer/blob/master/forseti-visualizer-ui/package-lock.json#L2052) file (assuming this is a dependency of something else listed in package.json).

**Comment by garrettwong** [comment]
Resolved by #49
