### ISSUE TITLE
Error after running "npm install" under forseti-api folder

### ISSUE THREAD

**Issue by rajathithan** [forseti-security/forseti-visualizer#54]
Hi All,

Can someone, please help me in fixing this issue, I am running the command with root privileges, but still it wont allow me to proceed further on the installation.

OS: Ubuntu
 node: v10.18.0
 npm : v6.13.4

============================================
/forseti-visualizer/forseti-api# npm install

> grpc@1.21.1 install /forseti-visualizer/forseti-api/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.21.1 and node@10.18.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/forseti-visualizer/forseti-api/node_modules/grpc/src/node'
gyp WARN EACCES current user ("rajathithan") does not have permission to access the dev dir "/root/.cache/node-gyp/10.18.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/forseti-visualizer/forseti-api/node_modules/grpc/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/forseti-visualizer/forseti-api/node_modules/grpc/.node-gyp'
gyp ERR! System Linux 5.0.0-1031-gcp
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/forseti-visualizer/forseti-api/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/forseti-visualizer/forseti-api/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /forseti-visualizer/forseti-api/node_modules/grpc
gyp ERR! node -v v10.18.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/forseti-visualizer/forseti-api/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/forseti-visualizer/forseti-api/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/forseti-visualizer/forseti-api/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.0.0-1031-gcp
node-pre-gyp ERR! command "/usr/local/bin/node" "/forseti-visualizer/forseti-api/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /forseti-visualizer/forseti-api/node_modules/grpc
node-pre-gyp ERR! node -v v10.18.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/forseti-visualizer/forseti-api/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/forseti-visualizer/forseti-api/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.21.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.21.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-06T04_04_51_074Z-debug.log

========================================================
Log file:
---------
21629 verbose stack Error: grpc@1.21.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
21629 verbose stack Exit status 1
21629 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
21629 verbose stack     at EventEmitter.emit (events.js:198:13)
21629 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
21629 verbose stack     at ChildProcess.emit (events.js:198:13)
21629 verbose stack     at maybeClose (internal/child_process.js:982:16)
21629 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
21630 verbose pkgid grpc@1.21.1
21631 verbose cwd /forseti-visualizer/forseti-api
21632 verbose Linux 5.0.0-1031-gcp
21633 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
21634 verbose node v10.18.0
21635 verbose npm  v6.13.4
21636 error code ELIFECYCLE
21637 error errno 1
21638 error grpc@1.21.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
21638 error Exit status 1
21639 error Failed at the grpc@1.21.1 install script.
21639 error This is probably not a problem with npm. There is likely additional logging output above.
21640 verbose exit [ 1, true ]

**Comment by rajathithan** [comment]
npm install --unsafe-perm, fixed the issue, because i was running the script as root.

**Comment by cyberbliss** [comment]
For anyone getting this error when running on OSX Catalina try uninstalling and reinstalling xcode command line tools as per this blog post here: https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d
