### ISSUE TITLE
Security Alerts for Dependencies (acorn & minimist)

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-visualizer#55]
![image](https://user-images.githubusercontent.com/6977544/76775598-cd79f800-6762-11ea-8e41-14bd14d5d2c2.png)

**Comment by dekuhn** [comment]
PTAL

**Comment by hshin-g** [comment]
@garrettwong Would you be able to jump in here? Looks like a quick fix for packages, but want to make sure that it doesn't break anything.

**Comment by garrettwong** [comment]
Yes will do, evaluating and will submit a PR when ready.

**Comment by blueandgold** [comment]
Hi @garrettwong please let us know how we can help to support these in the future, such as how to test as @hshin-g mentioned above.
